- name: ping the server
  hosts: web
  become: yes

  tasks:
  - name: ping the web server
    ansible.builtin.ping:

  - name: print the msg
    ansible.builtin.debug:
      msg: "hello world"

  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


